### ISSUE TITLE
TcpClient.sendMessage would raise NetworkOnMainThreadException

### ISSUE THREAD

**Issue by captainwong** [CatalinPrata/funcodetuts#2]
Hi!
First thankyou for your terrific example, its very easy to learn.

I've build my own android app based on your project 'AndroidTCPClient', everything went alright(connect/recv/show recvd msg...) except TcpClient.sendMessage.

When I click the button 'send' I got a NetworkOnMainThreadException, I don't know what to do but asking for your help. Would you please show me how to fix it?

**Comment by CatalinPrata** [comment]
Hi @captainwong !
Thanks for your feedback, it helps a lot! :)

About the issue, it seems to be because since API 10 or so the network calls should be done on a secondary thread. I will check the implementation and get back with some updates on the repository.

**Comment by CatalinPrata** [comment]
Ok, pushed a change, @captainwong please check it out when you have some time and let me know if it works now.

**Comment by captainwong** [comment]
@CatalinPrata Great work! Much better than my naive solution of creating new Thread for every SendMessage operation LOL. Once again, thanks for your job, it's really helpful for me.
